-- Criar tabela de vias (ruas)
CREATE TABLE ruas (
    id BIGINT PRIMARY KEY,
    nome TEXT,
    bairro TEXT,
    tipo TEXT,
    inicio TEXT,
    fim TEXT,
    largura NUMERIC,
    pavimento TEXT,
    comprimento_manual NUMERIC,
    obs TEXT,
    has_photos BOOLEAN DEFAULT false,
    photo_urls JSONB DEFAULT '[]'::jsonb,
    coords JSONB NOT NULL
);

-- Criar tabela de pinos
CREATE TABLE pinos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    color TEXT,
    lat NUMERIC NOT NULL,
    lng NUMERIC NOT NULL
);

-- Segurança: Habilitar Row Level Security (Leitura pública)
ALTER TABLE ruas ENABLE ROW LEVEL SECURITY;
ALTER TABLE pinos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura publica ruas" ON ruas FOR SELECT USING (true);
CREATE POLICY "Permitir leitura publica pinos" ON pinos FOR SELECT USING (true);
